name: Deployment Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Render GitHub Action
        uses: Bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000
      # - name: Trigger deployment
      #   run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
